on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/skattemelding/skattemelding:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: skattemelding
          service_account_email: github-actions@skattemelding.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Create Nix store
        run: |
          # Create with liberal rights, otherwise cache action will complain
          # about permission errors.
          sudo mkdir -p /nix/store
          sudo chmod -R 777 /nix

      - name: Cache Nix env
        uses: actions/cache@v2
        with:
          path: |
            # See https://github.com/actions/cache/pull/726
            /nix/store/**
            /nix/var/nix/*/*
            /nix/var/nix/db/*
            /nix/var/nix/db/*/**
            !/nix/var/nix/daemon-socket/socket
            !/nix/var/nix/userpool/*
            !/nix/var/nix/gc.lock
            !/nix/var/nix/db/big-lock
            !/nix/var/nix/db/reserved
          key: ${{ runner.os }}-nix-store

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-21.11

      - name: Build
        run: nix build

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
          
      - name: Load Docker image
        run: docker load < ./result

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy skattemelding --image $IMAGE_NAME --region europe-north1 --platform managed --port 8088